name:                 chatterbot
version:              0.1.0.0
visibility:           public
id:                   chatterbot-0.1.0.0-GYQOk4ro6lUAm6eqvrA5eA
key:                  chatterbot-0.1.0.0-GYQOk4ro6lUAm6eqvrA5eA
license:              BSD-3-Clause
copyright:            2019 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/chatterbot#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/chatterbot#readme>

abi:                  01accf756ed3b3f3ba5115e0d0fda372
exposed:              True
exposed-modules:      Chatterbot Utilities
hidden-modules:       Paths_chatterbot
import-dirs:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/chatterbot-0.1.0.0-GYQOk4ro6lUAm6eqvrA5eA"

library-dirs:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/chatterbot-0.1.0.0-GYQOk4ro6lUAm6eqvrA5eA"

library-dirs-static:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/chatterbot-0.1.0.0-GYQOk4ro6lUAm6eqvrA5eA"

dynamic-library-dirs:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3"

data-dir:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/share/x86_64-linux-ghc-9.10.3-b4c3/chatterbot-0.1.0.0"

hs-libraries:         HSchatterbot-0.1.0.0-GYQOk4ro6lUAm6eqvrA5eA
depends:
    HUnit-1.6.2.0-ICyHUTIMnBrctKBUsLbWR base-4.20.2.0-f074
    containers-0.7-d31f random-1.2.1.3-Jj6jenxRKXuHZkJZeY4OFL

haddock-interfaces:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/doc/chatterbot-0.1.0.0/chatterbot.haddock"

haddock-html:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/doc/chatterbot-0.1.0.0"
