name:                 memoization
version:              0.1.0.0
visibility:           public
id:                   memoization-0.1.0.0-Ax4RUhHhv0dXfDxuaJrng
key:                  memoization-0.1.0.0-Ax4RUhHhv0dXfDxuaJrng
license:              BSD-3-Clause
copyright:            2025 Noric Couderc
maintainer:           noric.couderc@cs.lth.se
author:               Noric Couderc
homepage:             https://github.com/githubuser/memoization#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/memoization#readme>

abi:                  575969f8607ca345540dbe810a8e3852
exposed:              True
exposed-modules:      Memoization MonadicMemoization StringAlignment
hidden-modules:       Paths_memoization
import-dirs:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/memoization-0.1.0.0-Ax4RUhHhv0dXfDxuaJrng"

library-dirs:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/memoization-0.1.0.0-Ax4RUhHhv0dXfDxuaJrng"

library-dirs-static:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/memoization-0.1.0.0-Ax4RUhHhv0dXfDxuaJrng"

dynamic-library-dirs:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3"

data-dir:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/share/x86_64-linux-ghc-9.10.3-b4c3/memoization-0.1.0.0"

hs-libraries:         HSmemoization-0.1.0.0-Ax4RUhHhv0dXfDxuaJrng
depends:
    base-4.20.2.0-f074 containers-0.7-d31f mtl-2.3.1-158c
    random-1.2.1.3-Jj6jenxRKXuHZkJZeY4OFL

haddock-interfaces:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/doc/memoization-0.1.0.0/memoization.haddock"

haddock-html:
    "/home/jonataneckeskog/Datateknik_LTH/Funktionell Programmering/EDAN40-laborationer/.stack-work/install/x86_64-linux/65926e05c0228b3f0fd67c515b60d67b6fce2688fd842490f580f88de1fb640e/9.10.3/doc/memoization-0.1.0.0"
